receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: otel-collector:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
