receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'flower'
          scrape_interval: 1s
          metrics_path: /metrics
          static_configs:
            - targets: ['flower:5555']
processors:
  batch:
    timeout: 10s
exporters:
  debug:
#    verbosity: detailed
  otlp:
    endpoint: "host.docker.internal:60737"
    tls:
      insecure: true
service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      exporters: [otlp, debug]
    traces:
      receivers: [otlp]
      exporters: [otlp, debug]
